hub:
  image:
    repository: selenium/hub
    tag: "4.7.2-20221219"
  replicas: 1
  service:
    type: LoadBalancer
    port: 4444

chromeNode:
  image:
    repository: selenium/node-chrome
    tag: "4.7.2-20221219"
  replicas: 3
  maxSessions: 2
