apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-selenium-hub
  labels:
    app: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
    - protocol: TCP
      port: {{ .Values.hub.service.port }}
      targetPort: 4444
      name: port0
    - protocol: TCP
      port: 4443
      targetPort: 4443
      name: port1
    - protocol: TCP
      port: 4442
      targetPort: 4442
      name: port2
  type: {{ .Values.hub.service.type }}
